# Generated by Django 2.1.1 on 2018-09-06 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_publication_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'publicacion', 'verbose_name_plural': 'publicaciones'},
        ),
        migrations.AddField(
            model_name='publication',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Publicacion'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='Imagen'),
        ),
    ]
