# Generated by Django 2.1.1 on 2018-09-08 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180906_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_users', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.ManyToManyField(related_name='get_category', to='blog.Category', verbose_name='Categorias'),
        ),
    ]
