# Generated by Django 2.0 on 2018-09-11 22:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180911_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
